import 'dart:async';
import 'dart:developer';
import 'dart:io';
import 'dart:math';
import 'dart:ui' as ui;

import 'package:flutter/material.dart';
import 'package:flutter/rendering.dart';
import 'package:flutter/services.dart';
import 'package:flutter_local_notifications/flutter_local_notifications.dart';
import 'package:flutter_polyline_points/flutter_polyline_points.dart';
import 'package:flutter_share/flutter_share.dart';
import 'package:flutter_spinkit/flutter_spinkit.dart';
import 'package:get/get.dart';
import 'package:google_fonts/google_fonts.dart';
import 'package:image_gallery_saver/image_gallery_saver.dart';
import 'package:image_picker/image_picker.dart';
import 'package:intl/intl.dart';
// import 'package:location/location.dart';
import 'package:material_design_icons_flutter/material_design_icons_flutter.dart';
import 'package:permission_handler/permission_handler.dart' as permission;
import 'package:supercharged/supercharged.dart';
import 'package:syncfusion_flutter_datepicker/datepicker.dart';
import 'package:url_launcher/url_launcher.dart';
import 'package:minutes_of_meeting/constants.dart';
import 'package:minutes_of_meeting/controllers/controllers.dart';
import 'package:minutes_of_meeting/models/models.dart';
import 'package:minutes_of_meeting/shared/shared.dart';
import 'package:minutes_of_meeting/ui/widgets/a_widgets.dart';
import 'package:minutes_of_meeting/utilities/a_utilities.dart';
// import 'package:youtube_player_iframe/youtube_player_iframe.dart';
import 'package:youtube_player_flutter/youtube_player_flutter.dart';
import 'package:webview_flutter/webview_flutter.dart';


part 'detail/detail_chat_page.dart';
part 'detail/detail_create_attendance_page.dart';
part 'detail/detail_report_page.dart';
// part 'detail/detail_track_page.dart';
part 'detail/detail_warnletter_page.dart';
part 'general_page.dart';
part 'main/annual_page.dart';
part 'main/home_page.dart';
part 'main/main_page.dart';
part 'main/profile_page.dart';
part 'main/report_page.dart';
part 'option/create_report_page.dart';
part 'option/option_calendar.dart';
part 'option/option_qr_scan_page.dart';
part 'option/option_warnletter.dart';
part 'profile/sign_in_page.dart';
part 'option/option_overtime.dart';
part 'option/option_leave_page.dart';
part 'option/option_payroll_page.dart';
part 'detail/detail_payroll_page.dart';
part 'detail/detail_overtime_page.dart';
part 'option/option_inventory_page.dart';
part 'option/option_inventoryreq.dart';
part 'option/option_meeting_page.dart';
part 'option/option_whistleblowing.dart';
// part 'option/option_forgetattendance_page.dart';
part 'detail/detail_knowladge.dart';
part 'option/option_knowladge_page.dart';
part 'option/option_reimbursement_page.dart';
part 'detail/detail_onsite_page.dart';
part 'option/option_tnc_page.dart';
part 'option/option_contact_page.dart';
part 'profile/auth_forget_password_page.dart';
part 'profile/auth_edit_profile_page.dart';
part 'profile/auth_edit_password_page.dart';
part 'profile/detail_profile_page.dart';
part 'option/option_notification_page.dart';
part 'option/accessloc_page.dart';